### ISSUE TITLE
Problems with CORS

### ISSUE THREAD

**Issue by fridomac** [HomeAutomationForGeeks/openhab-controlpanel#2]
Hello!

Followed the tutorial, can get the dashboard to load, but the widgets don´t work and don´t update.
In my Browsers Error Console I get the following error:

<code>XMLHttpRequest cannot load http://192.168.1.101:8080/rest/items/SideBoard/state. Origin http://192.168.1.101 is not allowed by Access-Control-Allow-Origin.</code>

Can you help? I suspect it has something to do with openHABs security settings...

Bye, Frido.

**Comment by HomeAutomationForGeeks** [comment]
Running the dashboard and OpenHAB on the same IP is of course the easiest solution :-)

Some quick googling turned up someone with a similar issue: https://groups.google.com/forum/#!topic/openhab/yvkRiqgBCM8

This is from 2 years ago - maybe the main OpenHAB code already has this as an option by now? Otherwise you might have to modify the OpenHAB source (by adding that CorsFilter class and using it in RESTApplication.java) and then build OpenHAB yourself.

**Comment by fridomac** [comment]
Hello,

Thanks for the quick reply. I am running both on the same IP. 
Will try the solution!

Bye, frido.

**Comment by HomeAutomationForGeeks** [comment]
Weird, I didn't expect this error when you're running both on the same IP, but there might be some other security setting in play. 

Only other thing I can think of is maybe if you're calling the dashboard in your browser via a name record instead of an IP (like "raspberry" or "localhost" instead of "192.168.1.101") then those would be considered different hosts?

**Comment by fridomac** [comment]
I address both over the same IP adress, OpenHAB lives at 192.168.1.101:8080 and the control panel at 192.168.1.101:80, the address above is what I put into the config section in index.html.
Will play around a little more...

**Comment by fridomac** [comment]
Found it: it is a bug introduced in openHAB 1.7.0:
https://github.com/openhab/openhab/pull/2672

Bye, Frido.

**Comment by fridomac** [comment]
Tested it, it is fixed with yesterdays 1.7.1 release, and works now.
